version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: gerck-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gerck
    ports:
      - "5432:5432"
    volumes:
      - gerck_pgdata:/var/lib/postgresql/data

volumes:
  gerck_pgdata:
